<?xml version="1.0" encoding="UTF-8"?>
<!--
/*********************************************************************
* Copyright (c) 2026 Contributors to the Eclipse Foundation.
*
* This program and the accompanying materials are made
* available under the terms of the Eclipse Public License 2.0
* which is available at https://www.eclipse.org/legal/epl-2.0/
*
* SPDX-License-Identifier: EPL-2.0
**********************************************************************/
-->
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="base" nsURI="https://www.daanse.org/spec/org.eclipse.daanse.cwm.model.cwmx.governance.base"
    nsPrefix="base">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="basePackage" value="org.eclipse.daanse.cwm.model.cwmx.governance"/>
    <details key="documentation" value="Gemeinsame Basistypen fuer Governance-Modelle (Datenschutz, Transparenz, KRITIS): generische Datenklassen/-felder sowie technisch-organisatorische Massnahmen (TOM)."/>
    <details key="documentation.en" value="Shared base types for governance models (data protection, transparency, KRITIS): generic data classes / fields and technical &amp; organizational measures (TOM)."/>
    <details key="caption.de" value="Governance-Basis"/>
    <details key="caption.en" value="Governance Base"/>
  </eAnnotations>
  <eSubpackages name="dataclass" nsURI="https://www.daanse.org/spec/org.eclipse.daanse.cwm.model.cwmx.governance.base/dataclass"
      nsPrefix="base.dataclass">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Generische Datenklassen und Datenfelder zur Klassifikation von Daten (verbal, Ecore- oder CWM-bezogen). Domaenenspezifische Erweiterungen (z.B. Datenschutzlevel, Personendaten-Kategorie) leben in den jeweiligen Domaenen-Modellen."/>
      <details key="documentation.en" value="Generic data classes and data fields for data classification (verbal, Ecore- or CWM-based). Domain-specific extensions (e.g. privacy level, personal-data category) live in their respective domain models."/>
      <details key="caption.de" value="Datenklassifikation"/>
      <details key="caption.en" value="Data Classification"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="DataClass" abstract="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value=" "/>
        <details key="documentation.en" value=" "/>
        <details key="caption.de" value="Datenklasse"/>
        <details key="caption.en" value="Data Class"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=" "/>
          <details key="documentation.en" value=" "/>
          <details key="caption.de" value="Name"/>
          <details key="caption.en" value="Name"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dataFields" upperBound="-1"
          eType="#//dataclass/DataField" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=" "/>
          <details key="documentation.en" value=" "/>
          <details key="caption.de" value="Datenfelder"/>
          <details key="caption.en" value="Data Fields"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VerbalDataClass" eSuperTypes="#//dataclass/DataClass">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Datenklasse ohne Modellreferenz (rein verbal)"/>
        <details key="documentation.en" value="Data class without model reference (verbal only)"/>
        <details key="caption.de" value="Verbale Datenklasse"/>
        <details key="caption.en" value="Verbal Data Class"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EcoreDataClass" eSuperTypes="#//dataclass/DataClass">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Datenklasse mit Referenz auf eine Ecore EClass"/>
        <details key="documentation.en" value="Data class with reference to an Ecore EClass"/>
        <details key="caption.de" value="Ecore-Datenklasse"/>
        <details key="caption.en" value="Ecore Data Class"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ecoreClass"
          eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Optionale Referenz auf eine Ecore EClass"/>
          <details key="documentation.en" value="Optional reference to an Ecore EClass"/>
          <details key="caption.de" value="Ecore-Klasse"/>
          <details key="caption.en" value="Ecore Class"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CwmDataClass" eSuperTypes="#//dataclass/DataClass">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Datenklasse mit Referenz auf einen CWM Classifier"/>
        <details key="documentation.en" value="Data class with reference to a CWM Classifier"/>
        <details key="caption.de" value="CWM-Datenklasse"/>
        <details key="caption.en" value="CWM Data Class"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="cwmClassifier"
          eType="ecore:EClass http://www.omg.org/spec/CWM/1.1/#//objectmodel/core/Classifier">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Optionale Referenz auf einen CWM Classifier (Table, Class, View etc.)"/>
          <details key="documentation.en" value="Optional reference to a CWM Classifier (Table, Class, View etc.)"/>
          <details key="caption.de" value="CWM-Classifier"/>
          <details key="caption.en" value="CWM Classifier"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataField" abstract="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value=" "/>
        <details key="documentation.en" value=" "/>
        <details key="caption.de" value="Datenfeld"/>
        <details key="caption.en" value="Data Field"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=" "/>
          <details key="documentation.en" value=" "/>
          <details key="caption.de" value="Name"/>
          <details key="caption.en" value="Name"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VerbalDataField" eSuperTypes="#//dataclass/DataField">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Datenfeld ohne Modellreferenz (rein verbal)"/>
        <details key="documentation.en" value="Data field without model reference (verbal only)"/>
        <details key="caption.de" value="Verbales Datenfeld"/>
        <details key="caption.en" value="Verbal Data Field"/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EcoreDataField" eSuperTypes="#//dataclass/DataField">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Datenfeld mit Referenz auf ein Ecore EStructuralFeature"/>
        <details key="documentation.en" value="Data field with reference to an Ecore EStructuralFeature"/>
        <details key="caption.de" value="Ecore-Datenfeld"/>
        <details key="caption.en" value="Ecore Data Field"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ecoreAttribute"
          eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Optionale Referenz auf ein Ecore EStructuralFeature"/>
          <details key="documentation.en" value="Optional reference to an Ecore EStructuralFeature"/>
          <details key="caption.de" value="Ecore-Attribut"/>
          <details key="caption.en" value="Ecore Attribute"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CwmDataField" eSuperTypes="#//dataclass/DataField">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Datenfeld mit Referenz auf ein CWM StructuralFeature"/>
        <details key="documentation.en" value="Data field with reference to a CWM StructuralFeature"/>
        <details key="caption.de" value="CWM-Datenfeld"/>
        <details key="caption.en" value="CWM Data Field"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="cwmAttribute"
          eType="ecore:EClass http://www.omg.org/spec/CWM/1.1/#//objectmodel/core/StructuralFeature">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Optionale Referenz auf ein CWM StructuralFeature (Column, Attribute, Field etc.)"/>
          <details key="documentation.en" value="Optional reference to a CWM StructuralFeature (Column, Attribute, Field etc.)"/>
          <details key="caption.de" value="CWM-Attribut"/>
          <details key="caption.en" value="CWM Attribute"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="tom" nsURI="https://www.daanse.org/spec/org.eclipse.daanse.cwm.model.cwmx.governance.base/tom"
      nsPrefix="base.tom">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Technisch-organisatorische Massnahmen (TOM): konkrete Massnahmen und wiederverwendbare Mustermassnahmen mit verantwortlicher Person."/>
      <details key="documentation.en" value="Technical and organizational measures (TOM): concrete measures and reusable templates with a responsible person."/>
      <details key="caption.de" value="TOM"/>
      <details key="caption.en" value="TOM"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="TOMMeasure">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value=" "/>
        <details key="documentation.en" value=" "/>
        <details key="caption.de" value="TOM-Maßnahme"/>
        <details key="caption.en" value="TOM Measure"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortname" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=" "/>
          <details key="documentation.en" value=" "/>
          <details key="caption.de" value="Kurzname"/>
          <details key="caption.en" value="Short Name"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=" "/>
          <details key="documentation.en" value=" "/>
          <details key="caption.de" value="Name"/>
          <details key="caption.en" value="Name"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=" "/>
          <details key="documentation.en" value=" "/>
          <details key="caption.de" value="Beschreibung"/>
          <details key="caption.en" value="Description"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="tomCategory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=" "/>
          <details key="documentation.en" value=" "/>
          <details key="caption.de" value="TOM-Kategorie"/>
          <details key="caption.en" value="TOM Category"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="responsiblePerson" lowerBound="1"
          eType="ecore:EClass http://www.omg.org/spec/CWM/1.1/#//foundation/businessinformation/ResponsibleParty">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=" "/>
          <details key="documentation.en" value=" "/>
          <details key="caption.de" value="Verantwortliche:r"/>
          <details key="caption.en" value="Responsible Person"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TOMTemplate">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value=" "/>
        <details key="documentation.en" value=" "/>
        <details key="caption.de" value="TOM-Mustermaßnahme"/>
        <details key="caption.en" value="TOM Template"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="shortname" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=" "/>
          <details key="documentation.en" value=" "/>
          <details key="caption.de" value="Kurzname"/>
          <details key="caption.en" value="Short Name"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=" "/>
          <details key="documentation.en" value=" "/>
          <details key="caption.de" value="Name"/>
          <details key="caption.en" value="Name"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=" "/>
          <details key="documentation.en" value=" "/>
          <details key="caption.de" value="Beschreibung"/>
          <details key="caption.en" value="Description"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="tomCategory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value=" "/>
          <details key="documentation.en" value=" "/>
          <details key="caption.de" value="TOM-Kategorie"/>
          <details key="caption.en" value="TOM Category"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
