<?xml version="1.0" encoding="UTF-8"?>
<!--
/*********************************************************************
* Copyright (c) 2026 Contributors to the Eclipse Foundation.
*
* This program and the accompanying materials are made
* available under the terms of the Eclipse Public License 2.0
* which is available at https://www.eclipse.org/legal/epl-2.0/
*
* SPDX-License-Identifier: EPL-2.0
**********************************************************************/
-->
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="transparency" nsURI="https://www.daanse.org/spec/org.eclipse.daanse.cwm.model.cwmx.governance.transparency"
    nsPrefix="transparency">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="basePackage" value="org.eclipse.daanse.cwm.model.cwmx.governance"/>
    <details key="documentation" value="Paket mit Modellen zur Bewertung von Transparenzpflichten gemaess Thueringer Transparenzgesetz (ThuerTG)"/>
    <details key="documentation.en" value="Package of models for transparency obligation assessment according to Thuringian Transparency Act (ThuerTG)"/>
    <details key="caption.de" value="Transparenzpflichten ThuerTG"/>
    <details key="caption.en" value="Transparency Obligations ThuerTG"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EEnum" name="PublicationMode">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Veroeffentlichungsart gemaess ThuerTG: proaktiv (§5/§6), auf Antrag (§9-§15) oder ausgeschlossen (§12/§13)"/>
      <details key="documentation.en" value="Publication mode according to ThuerTG: proactive (§5/§6), on request (§9-§15) or excluded (§12/§13)"/>
      <details key="caption.de" value="Veroeffentlichungsart"/>
      <details key="caption.en" value="Publication Mode"/>
    </eAnnotations>
    <eLiterals name="UNEDITED" literal="UNEDITED">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Nicht bearbeitet"/>
        <details key="documentation.en" value="Unedited"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="PROACTIVE_MANDATORY" value="1" literal="PROACTIVE_MANDATORY">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Proaktive Veroeffentlichungspflicht gemaess §5/§6 ThuerTG"/>
        <details key="documentation.en" value="Mandatory proactive publication according to §5/§6 ThuerTG"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="PROACTIVE_OPTIONAL" value="2" literal="PROACTIVE_OPTIONAL">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Freiwillige proaktive Veroeffentlichung"/>
        <details key="documentation.en" value="Voluntary proactive publication"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="ON_REQUEST" value="3" literal="ON_REQUEST">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Zugang nur auf Antrag gemaess §9-§15 ThuerTG"/>
        <details key="documentation.en" value="Access only on request according to §9-§15 ThuerTG"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="EXCLUDED" value="4" literal="EXCLUDED">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Von der Veroeffentlichung ausgeschlossen gemaess §12/§13 ThuerTG"/>
        <details key="documentation.en" value="Excluded from publication according to §12/§13 ThuerTG"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TransparencyCategory">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Informationskategorien gemaess §6 Abs. 3 Nr. 2 ThuerTG (a-r)"/>
      <details key="documentation.en" value="Information categories according to §6 para. 3 no. 2 ThuerTG (a-r)"/>
      <details key="caption.de" value="Transparenzkategorie"/>
      <details key="caption.en" value="Transparency Category"/>
    </eAnnotations>
    <eLiterals name="UNEDITED" literal="UNEDITED">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Nicht bearbeitet"/>
        <details key="documentation.en" value="Unedited"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="GESETZE" value="1" literal="GESETZE">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Gesetze und Rechtsverordnungen (§6 Abs. 3 Nr. 2 lit. a)"/>
        <details key="documentation.en" value="Laws and statutory orders (§6 para. 3 no. 2 lit. a)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="VERWALTUNGSVORSCHRIFTEN" value="2" literal="VERWALTUNGSVORSCHRIFTEN">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Verwaltungsvorschriften und allgemeine Weisungen (§6 Abs. 3 Nr. 2 lit. b)"/>
        <details key="documentation.en" value="Administrative regulations and general directives (§6 para. 3 no. 2 lit. b)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="KABINETTSBESCHLUESSE" value="3" literal="KABINETTSBESCHLUESSE">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Kabinettsbeschluesse (§6 Abs. 3 Nr. 2 lit. c)"/>
        <details key="documentation.en" value="Cabinet decisions (§6 para. 3 no. 2 lit. c)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="BERICHTE" value="4" literal="BERICHTE">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Berichte und Mitteilungen (§6 Abs. 3 Nr. 2 lit. d)"/>
        <details key="documentation.en" value="Reports and communications (§6 para. 3 no. 2 lit. d)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="SPONSORING" value="5" literal="SPONSORING">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Sponsoring (§6 Abs. 3 Nr. 2 lit. e)"/>
        <details key="documentation.en" value="Sponsoring (§6 para. 3 no. 2 lit. e)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="BETEILIGUNGEN" value="6" literal="BETEILIGUNGEN">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Beteiligungen an Unternehmen (§6 Abs. 3 Nr. 2 lit. f)"/>
        <details key="documentation.en" value="Corporate participations (§6 para. 3 no. 2 lit. f)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="TAETIGKEITSBERICHTE" value="7" literal="TAETIGKEITSBERICHTE">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Taetigkeitsberichte (§6 Abs. 3 Nr. 2 lit. g)"/>
        <details key="documentation.en" value="Activity reports (§6 para. 3 no. 2 lit. g)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="SITZUNGSBESCHLUESSE" value="8" literal="SITZUNGSBESCHLUESSE">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Sitzungsbeschluesse und -protokolle (§6 Abs. 3 Nr. 2 lit. h)"/>
        <details key="documentation.en" value="Meeting decisions and minutes (§6 para. 3 no. 2 lit. h)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="UMWELTINFORMATIONEN" value="9" literal="UMWELTINFORMATIONEN">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Umweltinformationen (§6 Abs. 3 Nr. 2 lit. i)"/>
        <details key="documentation.en" value="Environmental information (§6 para. 3 no. 2 lit. i)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="STATISTIKEN" value="10" literal="STATISTIKEN">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Statistiken und Datensammlungen (§6 Abs. 3 Nr. 2 lit. j)"/>
        <details key="documentation.en" value="Statistics and data collections (§6 para. 3 no. 2 lit. j)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="PLAENE" value="11" literal="PLAENE">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Plaene und Konzepte (§6 Abs. 3 Nr. 2 lit. k)"/>
        <details key="documentation.en" value="Plans and concepts (§6 para. 3 no. 2 lit. k)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="VERTRAEGE" value="12" literal="VERTRAEGE">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Vertraege der Daseinsvorsorge (§6 Abs. 3 Nr. 2 lit. l)"/>
        <details key="documentation.en" value="Public service contracts (§6 para. 3 no. 2 lit. l)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="ZUWENDUNGEN" value="13" literal="ZUWENDUNGEN">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Zuwendungen und Subventionen (§6 Abs. 3 Nr. 2 lit. m)"/>
        <details key="documentation.en" value="Grants and subsidies (§6 para. 3 no. 2 lit. m)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="VERGABEKAMMER" value="14" literal="VERGABEKAMMER">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Vergabekammer-Entscheidungen (§6 Abs. 3 Nr. 2 lit. n)"/>
        <details key="documentation.en" value="Public procurement chamber decisions (§6 para. 3 no. 2 lit. n)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="BEURTEILUNGEN" value="15" literal="BEURTEILUNGEN">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Beurteilungen und Bewertungen (§6 Abs. 3 Nr. 2 lit. o)"/>
        <details key="documentation.en" value="Assessments and evaluations (§6 para. 3 no. 2 lit. o)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="FINANZHILFEN" value="16" literal="FINANZHILFEN">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Finanzhilfen (§6 Abs. 3 Nr. 2 lit. p)"/>
        <details key="documentation.en" value="Financial aid (§6 para. 3 no. 2 lit. p)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="GUTACHTEN" value="17" literal="GUTACHTEN">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Gutachten und Studien (§6 Abs. 3 Nr. 2 lit. q)"/>
        <details key="documentation.en" value="Expert opinions and studies (§6 para. 3 no. 2 lit. q)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="SONSTIGE" value="18" literal="SONSTIGE">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Sonstige Informationen von oeffentlichem Interesse (§6 Abs. 3 Nr. 2 lit. r)"/>
        <details key="documentation.en" value="Other information of public interest (§6 para. 3 no. 2 lit. r)"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ExclusionGround">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Ausschlussgruende fuer die Veroeffentlichung gemaess §12 (oeffentliche Belange) und §13 (private Interessen) ThuerTG"/>
      <details key="documentation.en" value="Exclusion grounds for publication according to §12 (public interests) and §13 (private interests) ThuerTG"/>
      <details key="caption.de" value="Ausschlussgrund"/>
      <details key="caption.en" value="Exclusion Ground"/>
    </eAnnotations>
    <eLiterals name="UNEDITED" literal="UNEDITED">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Nicht bearbeitet"/>
        <details key="documentation.en" value="Unedited"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="NONE" value="1" literal="NONE">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Kein Ausschlussgrund — uneingeschraenkt veroeffentlichbar"/>
        <details key="documentation.en" value="No exclusion ground — unrestricted publication"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="PUBLIC_SECURITY" value="2" literal="PUBLIC_SECURITY">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Oeffentliche Sicherheit oder Ordnung (§12 Abs. 1 Nr. 1 ThuerTG)"/>
        <details key="documentation.en" value="Public security or order (§12 para. 1 no. 1 ThuerTG)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="CONFIDENTIALITY_OBLIGATION" value="3" literal="CONFIDENTIALITY_OBLIGATION">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Gesetzliche Geheimhaltungspflicht (§12 Abs. 1 Nr. 2 ThuerTG)"/>
        <details key="documentation.en" value="Statutory confidentiality obligation (§12 para. 1 no. 2 ThuerTG)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="ONGOING_PROCEEDINGS" value="4" literal="ONGOING_PROCEEDINGS">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Laufende Gerichts- oder Verwaltungsverfahren (§12 Abs. 1 Nr. 3 ThuerTG)"/>
        <details key="documentation.en" value="Ongoing court or administrative proceedings (§12 para. 1 no. 3 ThuerTG)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="SUPERVISORY_TASKS" value="5" literal="SUPERVISORY_TASKS">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Aufsichts- und Kontrollaufgaben (§12 Abs. 1 Nr. 4 ThuerTG)"/>
        <details key="documentation.en" value="Supervisory and control tasks (§12 para. 1 no. 4 ThuerTG)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="FISCAL_INTERESTS" value="6" literal="FISCAL_INTERESTS">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Fiskalische Interessen (§12 Abs. 1 Nr. 5 ThuerTG)"/>
        <details key="documentation.en" value="Fiscal interests (§12 para. 1 no. 5 ThuerTG)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="PERSONAL_DATA" value="7" literal="PERSONAL_DATA">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Personenbezogene Daten (§13 Abs. 1 ThuerTG)"/>
        <details key="documentation.en" value="Personal data (§13 para. 1 ThuerTG)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="BUSINESS_SECRET" value="8" literal="BUSINESS_SECRET">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Betriebs- und Geschaeftsgeheimnisse (§13 Abs. 2 ThuerTG)"/>
        <details key="documentation.en" value="Trade and business secrets (§13 para. 2 ThuerTG)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="DECISION_PREPARATION" value="9" literal="DECISION_PREPARATION">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Entscheidungsvorbereitung und Willensbildung (§12 Abs. 1 Nr. 6 ThuerTG)"/>
        <details key="documentation.en" value="Decision preparation and policy formulation (§12 para. 1 no. 6 ThuerTG)"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataFormatLevel">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Datenformat-Stufe gemaess §3 Abs. 3 und §7 Abs. 5 ThuerTG: maschinenlesbar, offene Standards"/>
      <details key="documentation.en" value="Data format level according to §3 para. 3 and §7 para. 5 ThuerTG: machine-readable, open standards"/>
      <details key="caption.de" value="Datenformat-Stufe"/>
      <details key="caption.en" value="Data Format Level"/>
    </eAnnotations>
    <eLiterals name="UNEDITED" literal="UNEDITED">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Nicht bearbeitet"/>
        <details key="documentation.en" value="Unedited"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="MACHINE_READABLE_OPEN" value="1" literal="MACHINE_READABLE_OPEN">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Maschinenlesbar in offenem Format (z.B. CSV, JSON, XML)"/>
        <details key="documentation.en" value="Machine-readable in open format (e.g. CSV, JSON, XML)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="MACHINE_READABLE_PROPRIETARY" value="2" literal="MACHINE_READABLE_PROPRIETARY">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Maschinenlesbar in proprietaerem Format (z.B. XLS, DOC)"/>
        <details key="documentation.en" value="Machine-readable in proprietary format (e.g. XLS, DOC)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="DIGITAL_NOT_MACHINE_READABLE" value="3" literal="DIGITAL_NOT_MACHINE_READABLE">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Digital, aber nicht maschinenlesbar (z.B. gescanntes PDF)"/>
        <details key="documentation.en" value="Digital but not machine-readable (e.g. scanned PDF)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="NOT_DIGITAL" value="4" literal="NOT_DIGITAL">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Nicht digital (nur in Papierform vorhanden)"/>
        <details key="documentation.en" value="Not digital (only available in paper form)"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AnonymizationLevel">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Anonymisierungsgrad fuer personenbezogene Daten gemaess §13 ThuerTG"/>
      <details key="documentation.en" value="Anonymization level for personal data according to §13 ThuerTG"/>
      <details key="caption.de" value="Anonymisierungsgrad"/>
      <details key="caption.en" value="Anonymization Level"/>
    </eAnnotations>
    <eLiterals name="UNEDITED" literal="UNEDITED">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Nicht bearbeitet"/>
        <details key="documentation.en" value="Unedited"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="NONE" value="1" literal="NONE">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Keine Anonymisierung erforderlich"/>
        <details key="documentation.en" value="No anonymization required"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="PSEUDONYMIZED" value="2" literal="PSEUDONYMIZED">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Pseudonymisiert (Zuordnung ueber Schluessel moeglich)"/>
        <details key="documentation.en" value="Pseudonymized (mapping via key possible)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="ANONYMIZED" value="3" literal="ANONYMIZED">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Vollstaendig anonymisiert (kein Personenbezug herstellbar)"/>
        <details key="documentation.en" value="Fully anonymized (no personal reference possible)"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="REDACTED" value="4" literal="REDACTED">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Geschwaerzt (betroffene Passagen entfernt)"/>
        <details key="documentation.en" value="Redacted (affected passages removed)"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransparencyAssessment">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Transparenzbewertung eines Datenbereichs gemaess Thueringer Transparenzgesetz (ThuerTG)"/>
      <details key="documentation.en" value="Transparency assessment of a data domain according to Thuringian Transparency Act (ThuerTG)"/>
      <details key="caption.de" value="Transparenzbewertung"/>
      <details key="caption.en" value="Transparency Assessment"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Name der Transparenzbewertung"/>
        <details key="documentation.en" value="Name of the transparency assessment"/>
        <details key="caption.de" value="Name"/>
        <details key="caption.en" value="Name"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Beschreibung des bewerteten Datenbereichs"/>
        <details key="documentation.en" value="Description of the assessed data domain"/>
        <details key="caption.de" value="Beschreibung"/>
        <details key="caption.en" value="Description"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="legalBasis" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Rechtsgrundlage der Transparenzpflicht (z.B. ThuerTG §6 Abs. 3)"/>
        <details key="documentation.en" value="Legal basis for the transparency obligation (e.g. ThuerTG §6 para. 3)"/>
        <details key="caption.de" value="Rechtsgrundlage"/>
        <details key="caption.en" value="Legal Basis"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validFrom" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Gueltigkeitsbeginn der Transparenzbewertung"/>
        <details key="documentation.en" value="Validity start date of the transparency assessment"/>
        <details key="caption.de" value="Gueltig ab"/>
        <details key="caption.en" value="Valid From"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastReview"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Datum der letzten Ueberpruefung"/>
        <details key="documentation.en" value="Date of the last review"/>
        <details key="caption.de" value="Letzte Ueberpruefung"/>
        <details key="caption.en" value="Last Review"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contactResponsible" lowerBound="1"
        eType="ecore:EClass http://www.omg.org/spec/CWM/1.1/#//foundation/businessinformation/ResponsibleParty">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Verantwortlicher Ansprechpartner fuer diese Transparenzbewertung"/>
        <details key="documentation.en" value="Responsible contact person for this transparency assessment"/>
        <details key="caption.de" value="Verantwortlicher"/>
        <details key="caption.en" value="Responsible Contact"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataClasses" upperBound="-1"
        eType="#//TransparencyClassRating" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Bewertete Transparenz-Datenklassen innerhalb dieser Bewertung"/>
        <details key="documentation.en" value="Assessed transparency data classes within this assessment"/>
        <details key="caption.de" value="Datenklassen"/>
        <details key="caption.en" value="Data Classes"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransparencyClassRating">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Transparenz-Bewertung einer Datenklasse gemaess Thueringer Transparenzgesetz (ThuerTG): verbindet eine generische Datenklasse (base/dataclass/DataClass) mit den transparenzrechtlichen Metadaten."/>
      <details key="documentation.en" value="Transparency rating of a data class according to Thuringian Transparency Act (ThuerTG): links a generic data class (base/dataclass/DataClass) to its transparency-law metadata."/>
      <details key="caption.de" value="Transparenz-Klassenbewertung"/>
      <details key="caption.en" value="Transparency Class Rating"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataClass" lowerBound="1"
        eType="ecore:EClass https://www.daanse.org/spec/org.eclipse.daanse.cwm.model.cwmx.governance.base#//dataclass/DataClass">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Bewertete Datenklasse"/>
        <details key="documentation.en" value="Rated data class"/>
        <details key="caption.de" value="Datenklasse"/>
        <details key="caption.en" value="Data Class"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="publicationMode" eType="#//PublicationMode">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Veroeffentlichungsart: proaktiv, auf Antrag oder ausgeschlossen"/>
        <details key="documentation.en" value="Publication mode: proactive, on request or excluded"/>
        <details key="caption.de" value="Veroeffentlichungsart"/>
        <details key="caption.en" value="Publication Mode"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transparencyCategory" eType="#//TransparencyCategory">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Informationskategorie gemaess §6 Abs. 3 Nr. 2 ThuerTG"/>
        <details key="documentation.en" value="Information category according to §6 para. 3 no. 2 ThuerTG"/>
        <details key="caption.de" value="Transparenzkategorie"/>
        <details key="caption.en" value="Transparency Category"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exclusionGround" eType="#//ExclusionGround">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Ausschlussgrund gemaess §12/§13 ThuerTG"/>
        <details key="documentation.en" value="Exclusion ground according to §12/§13 ThuerTG"/>
        <details key="caption.de" value="Ausschlussgrund"/>
        <details key="caption.en" value="Exclusion Ground"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataFormatLevel" eType="#//DataFormatLevel">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Datenformat-Stufe gemaess §3 Abs. 3 und §7 Abs. 5 ThuerTG"/>
        <details key="documentation.en" value="Data format level according to §3 para. 3 and §7 para. 5 ThuerTG"/>
        <details key="caption.de" value="Datenformat-Stufe"/>
        <details key="caption.en" value="Data Format Level"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anonymizationLevel" eType="#//AnonymizationLevel">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Anonymisierungsgrad fuer personenbezogene Daten gemaess §13 ThuerTG"/>
        <details key="documentation.en" value="Anonymization level for personal data according to §13 ThuerTG"/>
        <details key="caption.de" value="Anonymisierungsgrad"/>
        <details key="caption.en" value="Anonymization Level"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="retentionYears"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Vorhaltefrist in Jahren gemaess §7 Abs. 8 ThuerTG (mindestens 10 Jahre)"/>
        <details key="documentation.en" value="Retention period in years according to §7 para. 8 ThuerTG (minimum 10 years)"/>
        <details key="caption.de" value="Vorhaltefrist (Jahre)"/>
        <details key="caption.en" value="Retention Period (Years)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="legalReference"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Konkreter Paragraphen-Bezug (z.B. ThuerTG §6 Abs. 3 Nr. 2 lit. a)"/>
        <details key="documentation.en" value="Specific legal reference (e.g. ThuerTG §6 para. 3 no. 2 lit. a)"/>
        <details key="caption.de" value="Paragraphen-Bezug"/>
        <details key="caption.en" value="Legal Reference"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="publicationNote"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Freitext-Hinweis zur Veroeffentlichung"/>
        <details key="documentation.en" value="Free-text note regarding publication"/>
        <details key="caption.de" value="Veroeffentlichungshinweis"/>
        <details key="caption.en" value="Publication Note"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastReview"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Datum der letzten Ueberpruefung"/>
        <details key="documentation.en" value="Date of the last review"/>
        <details key="caption.de" value="Letzte Ueberpruefung"/>
        <details key="caption.en" value="Last Review"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataFields" upperBound="-1"
        eType="#//TransparencyFieldRating" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Transparenzbewertungen der Datenfelder, die zu dieser Datenklasse gehoeren"/>
        <details key="documentation.en" value="Transparency ratings of the data fields belonging to this data class"/>
        <details key="caption.de" value="Datenfeld-Bewertungen"/>
        <details key="caption.en" value="Field Ratings"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransparencyFieldRating">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Transparenz-Bewertung eines Datenfeldes gemaess Thueringer Transparenzgesetz (ThuerTG): verbindet ein generisches Datenfeld (base/dataclass/DataField) mit den transparenzrechtlichen Metadaten."/>
      <details key="documentation.en" value="Transparency rating of a data field according to Thuringian Transparency Act (ThuerTG): links a generic data field (base/dataclass/DataField) to its transparency-law metadata."/>
      <details key="caption.de" value="Transparenz-Feldbewertung"/>
      <details key="caption.en" value="Transparency Field Rating"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataField" lowerBound="1"
        eType="ecore:EClass https://www.daanse.org/spec/org.eclipse.daanse.cwm.model.cwmx.governance.base#//dataclass/DataField">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Bewertetes Datenfeld"/>
        <details key="documentation.en" value="Rated data field"/>
        <details key="caption.de" value="Datenfeld"/>
        <details key="caption.en" value="Data Field"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="publicationMode" eType="#//PublicationMode">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Veroeffentlichungsart des Datenfeldes"/>
        <details key="documentation.en" value="Publication mode of the data field"/>
        <details key="caption.de" value="Veroeffentlichungsart"/>
        <details key="caption.en" value="Publication Mode"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exclusionGround" eType="#//ExclusionGround">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Ausschlussgrund des Datenfeldes gemaess §12/§13 ThuerTG"/>
        <details key="documentation.en" value="Exclusion ground of the data field according to §12/§13 ThuerTG"/>
        <details key="caption.de" value="Ausschlussgrund"/>
        <details key="caption.en" value="Exclusion Ground"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anonymizationLevel" eType="#//AnonymizationLevel">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Anonymisierungsgrad des Datenfeldes gemaess §13 ThuerTG"/>
        <details key="documentation.en" value="Anonymization level of the data field according to §13 ThuerTG"/>
        <details key="caption.de" value="Anonymisierungsgrad"/>
        <details key="caption.en" value="Anonymization Level"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
